### ISSUE TITLE
Unable to build this sample application

### ISSUE THREAD

**Issue by anandakumarh** [ZoiPer/SDK_AndroidJavaExample#1]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

**Comment by CoderJava** [comment]
Yes. I have the same error.

**Comment by anandakumarh** [comment]
I have resolved this issue by changing 'aar' to 'jar in zdk.java-release file

This needs to be changed as 
configurations.maybeCreate("default")
artifacts.add("default", file('zdk.java-release.jar'))

**Comment by CoderJava** [comment]
> I have resolved this issue by changing 'aar' to 'jar in zdk.java-release file
> 
> This needs to be changed as
> configurations.maybeCreate("default")
> artifacts.add("default", file('zdk.java-release.jar'))

Hi It's work but, I cannot run my app. Error said 
`Transform output /Users/yudisetiawan/AndroidStudioProjects/SDK_AndroidJavaExample/zdk.java-release/zdk.java-release.jar must exist`

**Comment by ZoiPer** [comment]
Hello,

In order to get the zdk.java-release.aar file, you will need to contact us on zoiper.com for more information.

**Comment by CoderJava** [comment]
> Hello,
> 
> In order to get the zdk.java-release.aar file, you will need to contact us on zoiper.com for more information.

Thank you for your information.
