### ISSUE TITLE
run build error

### ISSUE THREAD

**Issue by ghost** [ZoiPer/SDK_AndroidJavaExample#2]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform artifact 'zdk.java-release.aar (project :zdk.java-release)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: app

**Comment by ZoiPer** [comment]
Hello, please contact us from the Contact form on Zoiper.com, so we can provide you with the SDK file to test the demo.
